name: "Flutter Dependencies"
description: "Installs Flutter and any other dependencies required for the build"
inputs:
  firebase_project_id:
    description: "Firebase project ID to configure"
    required: false
    default: ""
  firebase_service_account_key:
    description: "Firebase service account key JSON as a plain text string"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Get stable flutter
      uses: subosito/flutter-action@v2
      with:
        # NB! Keep up-to-date with the flutter version used for development
        flutter-version: "3.29.2"
        channel: "stable"

    - name: Prepare build directory
      shell: bash
      run: |
        flutter clean
        rm -rf build/*
        rm -rf web/src/mm2/*
        rm -rf web/src/kdfi/*
        rm -rf web/dist/*

    - name: Install Firebase CLI and FlutterFire CLI
      shell: bash
      run: |
        # Install Firebase CLI first
        npm install -g firebase-tools

        # Verify Firebase CLI installation
        firebase --version

        # Install FlutterFire CLI
        dart pub global activate flutterfire_cli

    - name: Configure Firebase
      shell: bash
      if: ${{ inputs.firebase_project_id != '' && inputs.firebase_service_account_key != '' }}
      run: |
        # Add flutterfire to PATH
        export PATH="$PATH":"$HOME/.pub-cache/bin"

        # Use the service account key directly (plain text)
        echo "Using service account key as plain text..."
        echo "${{ inputs.firebase_service_account_key }}" > /tmp/firebase-service-account.json

        # Authenticate with Firebase using service account
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json
        firebase use --add "${{ inputs.firebase_project_id }}"

        # Configure FlutterFire with the specified project
        flutterfire configure \
          --project=${{ inputs.firebase_project_id }} \
          --platforms=android,ios,macos,web \
          --yes
          
        # Clean up
        rm -f /tmp/firebase-service-account.json
