name: "Flutter Dependencies"
description: "Installs Flutter and any other dependencies required for the build"
inputs:
  firebase_project_id:
    description: "Firebase project ID to configure"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Get stable flutter
      uses: subosito/flutter-action@v2
      with:
        # NB! Keep up-to-date with the flutter version used for development
        flutter-version: "3.29.2"
        channel: "stable"

    - name: Prepare build directory
      shell: bash
      run: |
        flutter clean
        rm -rf build/*
        rm -rf web/src/mm2/*
        rm -rf web/src/kdfi/*
        rm -rf web/dist/*

    - name: Install FlutterFire CLI
      shell: bash
      run: |
        dart pub global activate flutterfire_cli

    - name: Configure Firebase
      shell: bash
      if: ${{ inputs.firebase_project_id != '' }}
      run: |
        # Add flutterfire to PATH
        export PATH="$PATH":"$HOME/.pub-cache/bin"

        # Configure FlutterFire with the specified project
        flutterfire configure \
          --project=${{ inputs.firebase_project_id }} \
          --platforms=android,ios,macos,web \
          --yes
