name: komodo_ui_kit
description: Komodo Wallet's UI Kit Flutter package.
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.35.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_theme:
    path: ../../app_theme/

  komodo_defi_types:
    git:
      url: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter.git
      path: packages/komodo_defi_types
      ref: dev

  komodo_ui:
    # path: ../../sdk/packages/komodo_ui # Requires symlink to the SDK in the root of the project
    git:
      url: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter.git
      path: packages/komodo_ui
      ref: dev

dev_dependencies:
  flutter_lints: ^5.0.0 # flutter.dev

flutter:
  uses-material-design: true

  assets:
    - lib/src/custom_icons/Custom.ttf

  fonts:
    - family: Custom
      fonts:
        - asset: lib/src/custom_icons/Custom.ttf
