name: firebase_core
description: No-op stub for F-Droid (android no native code)
version: 1000.0.0-fdroid
publish_to: "none"
environment:
  sdk: '>=2.17.0 <5.0.0'
dependencies:
  flutter:
    sdk: flutter
